### ISSUE TITLE
No module named wget

### ISSUE THREAD

**Issue by pizzadude** [LinuxSDA/Ciri-Xkcd-Comic-Downloader#6]
Under Linux Mint 18 (Ubuntu 16.04), attempting to download the archive results in the following error.

```
$ python Ciri.py --archive
Traceback (most recent call last):
  File "Ciri.py", line 10, in <module>
    import wget
ImportError: No module named wget
```

However, wget is in fact installed:
```
$ whereis wget
wget: /usr/bin/wget /usr/share/man/man1/wget.1.gz /usr/share/info/wget.info.gz

```

**Comment by LinuxSDA** [comment]
pip install wget or pip3 install wget

**Comment by pizzadude** [comment]
Yeah, I just figured that one out on my own. Thanks. :P 
Maybe put it in the readme?

**Comment by LinuxSDA** [comment]
Actually the installed wget is for bash. Python uses its own wget module, so, you have to pip install it.
